language: java
dist: focal
before_install:
  - sudo apt-get update
  - sudo apt-get install -y openjdk-17-jdk
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
